import { MD3LightTheme, MD3DarkTheme } from "react-native-paper";
import type { MD3Typescale } from "react-native-paper/lib/typescript/types";

const customFonts: MD3Typescale = {
  displayLarge: {
    fontFamily: "Montserrat_700Bold",
    fontWeight: "700",
    fontSize: 57,
    lineHeight: 64,
    letterSpacing: 0,
  },
  displayMedium: {
    fontFamily: "Montserrat_700Bold",
    fontWeight: "700",
    fontSize: 45,
    lineHeight: 52,
    letterSpacing: 0,
  },
  displaySmall: {
    fontFamily: "Montserrat_700Bold",
    fontWeight: "700",
    fontSize: 36,
    lineHeight: 44,
    letterSpacing: 0,
  },
  headlineLarge: {
    fontFamily: "Montserrat_700Bold",
    fontWeight: "700",
    fontSize: 32,
    lineHeight: 40,
    letterSpacing: 0,
  },
  headlineMedium: {
    fontFamily: "Montserrat_700Bold",
    fontWeight: "700",
    fontSize: 28,
    lineHeight: 36,
    letterSpacing: 0,
  },
  headlineSmall: {
    fontFamily: "Montserrat_700Bold",
    fontWeight: "700",
    fontSize: 24,
    lineHeight: 32,
    letterSpacing: 0,
  },
  titleLarge: {
    fontFamily: "Montserrat_700Bold",
    fontWeight: "700",
    fontSize: 22,
    lineHeight: 28,
    letterSpacing: 0,
  },
  titleMedium: {
    fontFamily: "Montserrat_700Bold",
    fontWeight: "700",
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0.15,
  },
  titleSmall: {
    fontFamily: "Montserrat_700Bold",
    fontWeight: "700",
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.1,
  },
  labelLarge: {
    fontFamily: "Montserrat_700Bold",
    fontWeight: "700",
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.1,
  },
  labelMedium: {
    fontFamily: "Montserrat_700Bold",
    fontWeight: "700",
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.5,
  },
  labelSmall: {
    fontFamily: "Montserrat_700Bold",
    fontWeight: "700",
    fontSize: 11,
    lineHeight: 16,
    letterSpacing: 0.5,
  },
  bodyLarge: {
    fontFamily: "Roboto_400Regular",
    fontWeight: "400",
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0.5,
  },
  bodyMedium: {
    fontFamily: "Roboto_400Regular",
    fontWeight: "400",
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.25,
  },
  bodySmall: {
    fontFamily: "Roboto_400Regular",
    fontWeight: "400",
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.4,
  },
  default: {
    fontFamily: "Roboto_400Regular",
    fontWeight: "400",
    letterSpacing: 0.5,
  },
};

export const CustomPaperLightTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: "#1565c0",
    onPrimary: "#ffffff",
    secondary: "#0d47a1",
    onSecondary: "#ffffff",
    background: "#e3f2fd",
    onBackground: "#0a192f",
    surface: "#90caf9",
    onSurface: "#0a192f",
    error: "#b00020",
    onError: "#ffffff",
    outline: "#1565c0",
    surfaceVariant: "#dbeafe",
    onSurfaceVariant: "#0a192f",
    shadow: "#000000",
    inverseSurface: "#0a192f",
    inverseOnSurface: "#e3f2fd",
    inversePrimary: "#90caf9",
  },
  fonts: customFonts,
};

export const CustomPaperDarkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: "#1e40af",
    onPrimary: "#ffffff",
    secondary: "#3b82f6",
    onSecondary: "#0a192f",
    background: "#0a192f",
    onBackground: "#f1f5f9",
    surface: "#60a5fa",
    onSurface: "#f1f5f9",
    error: "#cf6679",
    onError: "#000000",
    outline: "#3b82f6",
    surfaceVariant: "#1e3a8a",
    onSurfaceVariant: "#f1f5f9",
    shadow: "#000000",
    inverseSurface: "#e3f2fd",
    inverseOnSurface: "#0a192f",
    inversePrimary: "#60a5fa",
  },
  fonts: customFonts,
};
